api-service:
    container_name: api-service
    build: ./images/api-service
    environment:
        - ALLOW_OVERRIDE=true
    ports:
        - "80:80"
        # - "443:443"
    volumes:
        - ./src/api-service:/app
